#!/usr/bin/env bash

mountpoint=$1
components=("${@:2}")
currentdir="$(dirname "$(realpath "$0")")"

function help() {
    echo "Usage:"
    echo -e "\tgadi <MOUNTPOINT> [COMPONENTS]..."
    echo -e ""
}

if [[ -z "$mountpoint" ]]; then
    help
    exit 1
fi

function install_components() {
    components=$1

    for component in "${components[@]}"; do
        while read -r line; do
            if [ -z "$line" ]; then
                continue
            fi

            if [[ "$line" == "[category]" ]]; then
                components=()
                while read -r line; do
                    components+=($line)
                done
                install_components $components
            elif [[ "$line" == "[package]" ]]; then
                read -r pkgname
                read -r url
                read -r -a bins

                $currentdir/tbzei $mountpoint pains $pkgname $url $bins
            fi
        done < "$currentdir/components/$component.txt"
    done
}

install_components $components
